### ISSUE TITLE
Proposal to remove some potentially offensive words

### ISSUE THREAD

**Issue by smocherla-brex** [dustinkirkland/petname#3]
Hi there,

We use this library (through go-petname) to get some petnames and combine it with other user information (like <username>-<petname>). This works well most of the time but there are cases where the combination of both with words (animal related mostly) like `swine`, `termite`, `donkey` leads to a bad experience for users. So I was wondering if there would be a way to filter them out through the library through an argument or potentially remove these words (add it to the blacklist?).

Not sure if this belongs here or in https://github.com/dustinkirkland/golang-petname

**Comment by dustinkirkland** [comment]
Hi there, sure, it's easy enough for me to remove those 3 words.  I do maintain golang, python, and shell versions of these libraries, so I'll need to remove it from all of them.

**Comment by smocherla-brex** [comment]
Thanks for accepting the request.
